# 应用名称
spring:
  application:
    name: small
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8

  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/small?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    dynamic:
      lazy: true

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.small.small.mapper



